# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20161010_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='name'),
        ),
    ]
